name: Build and Deploy Next.js

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18"

            - name: Install dependencies
              run: yarn install

            - name: Build
              run: yarn build

    deploy:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to hosting service
              run: yarn deploy
